-- 조회 : 저자ID, 저자명, 카테고리, 매출액
-- 그룹 : 저자별, 카테고리별
-- 정렬 : 저자ID 기준, 카테고리 기준 내림차순

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES S 
    LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
    LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;