-- 조회 : CART_ID
-- 조건 : 우유와 요거트를 동시에 구입
-- 정렬 : CART_ID 기준

SELECT DISTINCT(CART_ID) AS CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk')
    AND CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt')
ORDER BY CART_ID;