-- 조회 : ITEM_ID, ITEM_NAME, RARITY
-- 조건 : 더 이상 업그레이드할 수 없는 아이템
-- 정렬 : ITEM_ID 기준 내림차순

WITH CTE1 AS (
    SELECT P.ITEM_ID
    FROM ITEM_INFO P LEFT JOIN ITEM_TREE C ON P.ITEM_ID = C.PARENT_ITEM_ID
    WHERE C.PARENT_ITEM_ID IS NULL
), CTE2 AS (
    SELECT I.ITEM_ID, ITEM_NAME, RARITY
    FROM ITEM_INFO I JOIN CTE1 C1 ON I.ITEM_ID = C1.ITEM_ID
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM CTE2
ORDER BY ITEM_ID DESC;