-- 조회 : ITEM_ID, ITEM_NAME, RARITY
-- 조건 : 더 이상 업그레이드할 수 없는 아이템
-- 정렬 : ITEM_ID 기준 내림차순

SELECT P.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO P LEFT JOIN ITEM_TREE C ON P.ITEM_ID = C.PARENT_ITEM_ID
WHERE C.PARENT_ITEM_ID IS NULL
ORDER BY P.ITEM_ID DESC;