-- 조회: 아이템ID, 아이템명, 아이템의 희귀도
-- 조건: 더 이상 업그레이드 할 수 없는 아이템 C.PARENT_ITEM_ID IS NULL
-- 정렬: 아이템ID 기준 내림차순

SELECT P.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO P LEFT JOIN ITEM_TREE C ON P.ITEM_ID = C.PARENT_ITEM_ID
WHERE C.PARENT_ITEM_ID IS NULL
ORDER BY P.ITEM_ID DESC;