-- 조회 : 대장균 개체의 ID, 자식의 수
-- 자식의 수 : 자식이 없다면 0
-- 정렬 : 개체의 ID 기준
SELECT P.ID, IFNULL(COUNT(C.PARENT_ID), 0) AS CHILD_COUNT
FROM ECOLI_DATA P LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID;