-- 조회 : ID, CHILD_COUNT
-- CHILD_COUNT : 자식이 없다면 0으로 출력
-- 정렬 : ID 기준

WITH CTE AS (
    SELECT P.ID, COUNT(C.PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA P LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
    GROUP BY P.ID
)

SELECT ID, CHILD_COUNT
FROM CTE
ORDER BY ID;
