-- 조회 : 상품코드, 매출액(판매가*판매량)
-- 그룹 : 상품코드
-- 정렬 : 매출액 기준 내림차순, 상품코드 기준

SELECT PRODUCT_CODE, PRICE*SUM(SALES_AMOUNT) AS 'SALES'
FROM OFFLINE_SALE S LEFT JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;