SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM ONLINE_SALE
        UNION ALL
        SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
        FROM OFFLINE_SALE) AS T
WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;