-- 조회 : ANIMAL_ID, NAME
-- 조건 : 입양을 간 동물 중 보호 기간이 가장 길었던 동물 두 마리
-- 정렬 : 보호 기간이 긴 순

WITH TEMP AS (
    SELECT O.ANIMAL_ID,
        O.NAME,
        DATEDIFF(O.DATETIME, I.DATETIME) AS DURATION,
        RANK() OVER(ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC) AS RNK
    FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
)

SELECT ANIMAL_ID, NAME
FROM TEMP
WHERE RNK <= 2
ORDER BY DURATION DESC;