-- 조회 : 개체ID, 분류된 이름
-- 정렬 : 개체ID 기준 오름차순
SELECT ID, 
    CASE
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 4 THEN 'CRITICAL'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 3 THEN 'HIGH'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 2 THEN 'MEDIUM'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 1 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;
     


# CASE
#     WHEN RNK <= COUNT(*) * 0.25 THEN 'CRITICAL'
#     WHEN RNK <= COUNT(*) * 0.5 THEN 'HIGH'
#     WHEN RNK <= COUNT(*) * 0.75 THEN 'MEDIUM'
#     ELSE 'LOW'
# END AS COLONY_NAME