-- 조회 : ID, COLONY_NAME
-- COLONY_NAME : 상위 ~25% 이내 THEN CRITICAL, ~50% 이내 THEN HIGH, ~75% 이내 THEN MEDIUM, ~100% 이내 LOW
-- 정렬 : ID 기준

WITH CTE AS (
    SELECT ID,
        CASE
            WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) <= 0.25 THEN 'CRITICAL' 
            WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) <= 0.5 THEN 'HIGH'
            WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
        END AS COLONY_NAME
    FROM ECOLI_DATA
)

SELECT *
FROM CTE
ORDER BY ID;