-- 조회 : ANIMAL_ID, ANIMAL_TYPE, NAME
-- 조건 : 보호소에 들어올 당시에는 중성화되지 않았지만 나갈 당시에는 중성화된 동물
-- 정렬 : ANIMAL_ID 기준

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
    AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID;