-- 조회 : 년, 월, 성별, 회원수
-- 조건 : 성별 정보가 없는 경우 결과에서 제외
-- 그룹 : 년, 월, 성별 별
-- 정렬 : 년, 월, 성별 기준
SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT(S.USER_ID)) AS USERS
FROM ONLINE_SALE S LEFT JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER;