-- 조회 : 년, 월, 성별, 상품을 구매한 회원 수
-- 조건 : 성별이 NULL이 아닌 회원
-- 그룹 : 년, 월, 성별
-- 정렬 : 년 기준, 월 기준, 성별 기준
SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT(S.USER_ID)) AS USERS
FROM ONLINE_SALE S LEFT JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY DATE_FORMAT(SALES_DATE, '%Y%m'), GENDER
ORDER BY DATE_FORMAT(SALES_DATE, '%Y%m'), GENDER