-- 조회 : 대여기간 >= 30 ? 장기대여 : 단기 대여 AS RENT_TYPE
-- 조건 : 대여 시작일이 2022년 9월
-- 정렬 : 대여 기록 ID 기준 내림차순
SELECT HISTORY_ID, 
    CAR_ID, 
    DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
    DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) >= 29 THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y%m') = '202209'
ORDER BY HISTORY_ID DESC;