-- 조회 : ID, 이름
-- 조건 : 입양을 갔는데 보호소에 들어온 기록이 없는 동물
-- 정렬 : ID 기준
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;