-- 조회 : 동물ID, 이름
-- 조건 : 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물
-- 정렬 : 동물ID 기준

WITH CTE AS (
    SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE I.ANIMAL_ID IS NULL
)

SELECT ANIMAL_ID, NAME
FROM CTE
ORDER BY ANIMAL_ID;