-- 조회 : 물고기 종류별 이름 AS FISH_NAME, 잡은 수 AS FISH_COUNT
-- 그룹 : 물고기 종류
-- 정렬 : 잡은 수 기준 내림차순
SELECT COUNT(i.ID) AS FISH_COUNT, n.FISH_NAME AS FISH_NAME
FROM FISH_INFO i LEFT JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE 
GROUP BY n.FISH_NAME
ORDER BY FISH_COUNT DESC;