-- 조회 : 잡은 수, 물고기 이름
-- 그룹 : 종류
-- 정렬 : 잡은 수 기준 내림차순

SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO F LEFT JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC;