-- 조회 : CAR_ID, AVAILABILITY
-- AVAILABILITY : 2022년 10월 16일에 대여 중 THEN 대여중, ELSE 대여가능
-- 정렬 : CAR_ID 기준 내림차순

WITH CTE1 AS (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
), CTE2 AS (
    SELECT H.CAR_ID, 
        CASE 
            WHEN C.CAR_ID IS NOT NULL THEN'대여중'
            ELSE '대여 가능'
        END AS 'AVAILABILITY'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CTE1 C ON H.CAR_ID = C.CAR_ID
    GROUP BY H.CAR_ID
)

SELECT CAR_ID, AVAILABILITY
FROM CTE2
ORDER BY CAR_ID DESC;