-- 조회 : ID, SIZE
-- SIZE : 크기 <= 100 THEN LOW, 크키 <= 1000 THEN MEDIUM, ELSE HIGH
-- 정렬 : ID 기준

WITH CTE AS (
    SELECT ID,
        CASE
            WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
            WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
            ELSE 'HIGH'
        END AS SIZE
    FROM ECOLI_DATA
)

SELECT ID, SIZE
FROM CTE
ORDER BY ID;
