-- 조회 : 분기, 분기별 분화된 대장균의 개체의 총 수 AS ECOLI_COUNT
-- 분기 : + Q
-- 정렬 : 분기 기준 오름차순
SELECT CONCAT(Q, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (SELECT 
        CASE WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN 1
             WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN 2
             WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN 3
             ELSE 4
        END AS Q
      FROM ECOLI_DATA
    ) AS TEMP
GROUP BY Q
ORDER BY Q;

