-- 조회 : 이름, 보호 시작일
-- 조건 : 입양을 못 간 동물 중 가장 오래 보호소에 있었던 동물 3마리
-- 정렬 : 보호 시작일 기준

WITH TEMP AS (
    SELECT I.ANIMAL_ID, 
        I.DATETIME,
        I.NAME,
        RANK() OVER(ORDER BY I.DATETIME) AS RNK
    FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
)

SELECT NAME, DATETIME
FROM TEMP
WHERE RNK <= 3
ORDER BY DATETIME;