-- 조회 : 식품ID, 식품 이름, 총매출
-- 조건 : 생산일자가 2022년 5월
-- 정렬 : 총매출 기준 내림차순, 식품ID 기준

SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
