-- 조회 : 맛
-- 조건 : 7월 총 주문량 + 상반기 총 주문량이 큰 상위 3개의 맛

SELECT FLAVOR
FROM (SELECT H.FLAVOR,
            ROW_NUMBER() OVER(ORDER BY HALF_SUM + JULY_SUM DESC) AS RNK
        FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS HALF_SUM FROM FIRST_HALF GROUP BY FLAVOR) AS H
            JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM FROM JULY GROUP BY FLAVOR) AS J
            ON H.FLAVOR = J.FLAVOR) AS TEMP
WHERE RNK <= 3;
