WITH CTE AS (
    SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
    FROM APPOINTMENT A LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
        LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO
    WHERE APNT_YMD REGEXP '^2022-04-13'
        AND D.MCDP_CD REGEXP '^CS'
        AND APNT_CNCL_YN REGEXP '^N'
)

SELECT *
FROM CTE
ORDER BY APNT_YMD;