-- 조회 : 회원ID, 이름, 성별, 생년월일
-- 조건 : 전화번호 IS NOT NULL
-- 정렬 : 회원ID 기준

SELECT MEMBER_ID, 
    MEMBER_NAME, 
    GENDER, 
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
    AND MONTH(DATE_OF_BIRTH) = 3
    AND GENDER = 'W'
ORDER BY MEMBER_ID;