-- 조회 : 회원ID, 닉네임, 총거래금액
-- 조건 : 완료된 중고 거래의 총 금액이 70만원 이상인 사람
-- 정렬 : 총거래금액 기준

WITH CTE AS (
    SELECT U.USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B LEFT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
    WHERE STATUS REGEXP '^DONE'
    GROUP BY U.USER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM CTE
ORDER BY TOTAL_SALES;