-- 조회 : 시간대, 수
-- 그룹 : 시간대
-- 정렬 : 시간대
SELECT DATE_FORMAT(DATETIME, '%H') as 'HOUR', COUNT(ANIMAL_ID) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') BETWEEN '09' AND '19'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY HOUR;