-- 조회 : MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
-- 조건 : 리뷰를 가장 많이 작성한 회원의 리뷰들
-- 정렬 : REVIEW_DATE 기준, REVIEW_TEXT 기준

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW R JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
    JOIN (SELECT MEMBER_ID, RANK() OVER(ORDER BY CNT DESC) AS RNK
            FROM (SELECT MEMBER_ID, COUNT(*) AS CNT FROM REST_REVIEW GROUP BY MEMBER_ID) AS T) AS SUB
    ON P.MEMBER_ID = SUB.MEMBER_ID
WHERE RNK = 1
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;


