-- 조회 : 동물ID, 이름
-- 조건 : 보호 시작일보다 입양일이 더 빠른 동물
-- 정렬 : 보호 시작일

WITH TEMP AS (
    SELECT I.ANIMAL_ID, I.NAME, I.DATETIME
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.DATETIME < I.DATETIME
)

SELECT ANIMAL_ID, NAME
FROM TEMP
ORDER BY DATETIME;