-- 조회 : 월, CAR_ID, 총 대여 횟수
-- 총 대여 횟수 : 총 대여 횟수가 0인 경우 결과에서 제외
-- 조건 : 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
-- 정렬 : 월 기준, CAR_ID 기준 내림차순

WITH CTE1 AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
), CTE2 AS (
    SELECT MONTH(START_DATE) AS MONTH,
        H.CAR_ID,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CTE1 C1 ON H.CAR_ID = C1.CAR_ID
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH, CAR_ID
)

SELECT MONTH, CAR_ID, RECORDS
FROM CTE2
ORDER BY MONTH, CAR_ID DESC;
