-- 조회: 월, CAR_ID, 총 대여 횟수 AS RECORDS
-- 서브쿼리: 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들
-- 조건: 월별 총 대여 횟수가 0인 결과는 제외
-- 정렬: 월 기준, CAR_ID 기준 내림차순

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
                GROUP BY CAR_ID
                HAVING COUNT(*) >= 5)
    AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH, CAR_ID DESC;

