-- 조회 : 개발자ID, 이메일, 이름, 성
-- 조건 : Python 혹은 C# 스킬 보유
-- 정렬 : ID 기준

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
ORDER BY ID;