-- 조회 : 연도, 편차, ID
-- 편차 : 연도별 가장 큰 대장균 크기 - 각 대장균 크기
-- 정렬 : 대장균 크기의 편차 기준
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,  
    ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;
