-- 조회 : 맛
-- 조건 : 총주문량이 3000 초과 && 아이스크림 주 성분이 과일
-- 정렬 : 총주문량 내림차순
SELECT F.FLAVOR
FROM FIRST_HALF AS F 
LEFT OUTER JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 && I.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY TOTAL_ORDER DESC;