-- 조회 : 자동차ID
-- 조건 : 자동차 종류가 세단이면서 10월에 대여를 시작한 기록이 있는 자동차ID
-- 정렬 : 자동차ID 기준 내림차순

WITH TEMP AS (
    SELECT DISTINCT(C.CAR_ID) AS CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        LEFT JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE REGEXP '^세단'
        AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
)

SELECT CAR_ID
FROM TEMP
ORDER BY CAR_ID DESC;