-- 조회 : 자동차ID
-- 조건 : 세단, 10월에 대여 시작
-- 정렬 : 자동차ID 기준 내림차순

SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '세단' 
    AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;
