-- 조회 : ID, FISH_NAME, LENGTH
-- 조건 : 물고기 종류별 가장 큰 물고기
-- 그룹 : 물고기 종류별
-- 정렬 : ID 기준

WITH CTE1 AS (
    SELECT I.FISH_TYPE, FISH_NAME, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY I.FISH_TYPE, FISH_NAME
), CTE2 AS (
    SELECT ID, FISH_NAME, C1.LENGTH
    FROM FISH_INFO I LEFT JOIN CTE1 C1 ON I.FISH_TYPE = C1.FISH_TYPE
    WHERE I.LENGTH = C1.LENGTH
)

SELECT ID, FISH_NAME, LENGTH
FROM CTE2
ORDER BY ID;