-- 조회 : 도서ID, 출판일
-- 조건 : 2021년 출판 && 카테고리 '인문'
-- 정렬 : 출판일 기준 오름차순
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = '2021' && CATEGORY LIKE '인문'
ORDER BY PUBLISHED_DATE;