# 2022년도 한 해 평가 점수가 가장 높은 사원 정보 조회
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM HR_EMPLOYEES AS E
JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE 
        FROM HR_GRADE
        GROUP BY EMP_NO) AS G
ON E.EMP_NO = G.EMP_NO
ORDER BY G.SCORE DESC
LIMIT 1;
