-- 조회 : 점수, 사번, 성명, 직책, 이메일
-- 조건 : 2022년도 한 해 평가 점수가 가장 높은 사원

SELECT SUM(SCORE) AS SCORE, G.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE G LEFT JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;