-- 조회 : 성분 타입, 성분 타입 별 총주문량 AS TOTAL_ORDER
-- 정렬 : 총주문량 기준
SELECT i.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF f LEFT JOIN ICECREAM_INFO i ON f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER);


