-- 조회 : 부서ID, 영문 부서명, 평균 연봉
-- 평균 연봉 : 소수점 첫째 자리에서 반올림
-- 그룹 : 부서별
-- 정렬 : 평균 연봉 기준 내림차순

WITH CTE AS (
    SELECT D.DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES E LEFT JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
    GROUP BY D.DEPT_ID
)

SELECT DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM CTE
ORDER BY AVG_SAL DESC;


