-- 조회 : FILE_PATH
-- FILE_PATH : /home/grep/src/BOARD_ID/FILE_IDFILE_NAMEFILE_EXT
-- 조건 : 조회수가 가장 높은 중고거래 게시물
-- 정렬 : FILD_ID 기준 내림차순

WITH CTE1 AS (
    SELECT BOARD_ID,
        RANK() OVER(ORDER BY VIEWS DESC) AS RNK
    FROM USED_GOODS_BOARD
), CTE2 AS (
    SELECT FILE_ID, FILE_EXT, FILE_NAME, F.BOARD_ID
    FROM USED_GOODS_FILE F LEFT JOIN CTE1 C1 ON F.BOARD_ID = C1.BOARD_ID
    WHERE RNK = 1
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM CTE2
ORDER BY FILE_ID DESC;