-- 조회 : 카테고리, 총 판매량
-- 그룹 : 연도월, 카테고리
-- 해빙 : 2022년 1월
-- 정렬 : 카테고리명 기준 

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202201'
GROUP BY CATEGORY
ORDER BY CATEGORY;