-- 조회 : 카테고리명, 카테고리 총 판매량
-- 조건 : 2022년 1월
-- 그룹 : 카테고리별
-- 정렬 : 카테고리명 기준
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;