-- 조회 : 카테고리, 총 판매량
-- 조건 : 2022년 1월 판매
-- 정렬 : 카테고리 기준

WITH TEMP AS (
    SELECT B.BOOK_ID, CATEGORY, SALES_DATE, SALES
    FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
)

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM TEMP
WHERE SALES_DATE REGEXP '^2022-01' 
GROUP BY CATEGORY
ORDER BY CATEGORY;